name: Manual testing for CI/CD

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3.3.0
      - name: Set up DB
        run: docker compose up -d
      - name: Build
        run: mvn --batch-mode package
      - name: Test
        run: mvn test
