name: Testing for CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Set up DB
        run: docker compose up -d
      - name: Build and test
        run: mvn --batch-mode package
