name: Testing for CI/CD

on:
  workflow_dispatch:
  # Allows the workflow to be manually triggered from the GitHub Actions UI.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build-Test:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3.3.0
      - name: Set up DB
        run: docker compose up -d
      - name: Build
        run: mvn compile
      - name: Test
        run: mvn test
